const assert=require('assert').strict,E=require('../web/public/engine.js');
function test(name,fn){try{fn();console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);process.exitCode=1;}}
function run(p,seconds){for(let i=0;i<seconds*120;i++)E.step(p,1/120,E.level(p.level).seed,i/120,()=>{});return p;}
test('jump limits increase at levels 6, 11 and 20',()=>{for(const stage of E.levels){const limit=stage.id<=5?3:stage.id<=10?4:stage.id<=19?5:6;assert.equal(stage.maxJumps,limit);const p=E.player('jonah',stage.id);p.x=-1000;p.edge=-1230;for(let i=0;i<limit;i++)assert.ok(E.jump(p));assert.equal(E.jump(p),false);run(p,.8);assert.equal(p.jumps,0);assert.ok(E.jump(p));}});
test('long crossings require four, five and six timed jumps',()=>{for(const id of [6,11,20]){const stage=E.level(id),gap=E.obstacles(stage.seed,0,stage.length,id).find(o=>o.jumpsRequired===stage.maxJumps);assert.ok(gap);function cross(limit){const p=E.player('jonah',id);p.x=gap.x-5;p.edge=p.x-(140+(stage.maxJumps-3)*30);E.jump(p);for(let i=0;i<600&&p.alive&&p.x<gap.x+gap.width+2;i++){if(p.jumps<limit&&p.x>=gap.x+31+(p.jumps-1)*39)E.jump(p);E.step(p,1/120,stage.seed,i/120);}return p;}assert.equal(cross(stage.maxJumps-1).alive,false);const cleared=cross(stage.maxJumps);assert.ok(cleared.alive);assert.ok(cleared.x>gap.x+gap.width);}});
test('25 levels increase distance, pace, pressure and obstacle frequency',()=>{assert.equal(E.levels.length,25);for(let i=1;i<25;i++){assert.ok(E.levels[i].length>E.levels[i-1].length);assert.ok(E.levels[i].scale>E.levels[i-1].scale);assert.ok(E.levels[i].pressure>E.levels[i-1].pressure);assert.ok(E.levels[i].spacing<E.levels[i-1].spacing);}});
test('walking alone loses to the bridge for every traveler',()=>{for(const c of Object.keys(E.travelers)){const p=E.player(c);p.x=-1000;p.edge=-1052;run(p,54/E.level(1).pressure);assert.equal(p.alive,false);assert.equal(p.reason,'The falling bridge caught up.');}});
test('sprint earns space and costs flame; walking recovers flame but loses space',()=>{for(const c of Object.keys(E.travelers)){const p=E.player(c);p.x=-500;p.edge=-552;p.sprint=true;run(p,1);const lead=p.x-p.edge,flame=p.flame;assert.ok(lead>52);assert.ok(flame<100);p.sprint=false;run(p,1);assert.ok(p.x-p.edge<lead);assert.ok(p.flame>flame);assert.ok(p.alive);}});
test('triple jump permits two air boosts and resets on landing',()=>{const p=E.player();p.x=-500;p.edge=-640;assert.ok(E.jump(p));run(p,.2);assert.ok(E.jump(p));assert.equal(p.jumps,2);assert.ok(E.jump(p));assert.equal(p.jumps,3);assert.equal(E.jump(p),false);run(p,1.2);assert.equal(p.y,0);assert.equal(p.jumps,0);});
test('normal gaps need one jump; sparse 62 m breaks need two',()=>{for(const stage of E.levels){const gaps=E.obstacles(stage.seed,0,stage.length,stage.id).filter(o=>o.type==='gap');assert.ok(gaps.some(o=>!o.wide));assert.equal(stage.theme,stage.id%2?'dawn':'night');}const medium=E.level(6),gap=E.obstacles(medium.seed,0,medium.length,6).find(o=>o.wide);assert.equal(gap.width,62);let p=E.player('jonah',6);p.x=gap.x-3;p.edge=p.x-140;E.jump(p);run(p,1.1);assert.equal(p.alive,false);p=E.player('jonah',6);p.x=gap.x-3;p.edge=p.x-140;E.jump(p);run(p,.58);E.jump(p);run(p,.6);assert.ok(p.alive);assert.ok(p.x>gap.x+gap.width);const normal=E.obstacles(71,0,1800)[0];p=E.player();p.x=normal.x-3;p.edge=p.x-140;E.jump(p);run(p,.48);assert.ok(p.alive);assert.ok(p.x>normal.x+normal.width);});
test('six named travelers and Jonah default',()=>{assert.equal(Object.keys(E.travelers).length,6);assert.equal(E.player().character,'jonah');assert.equal(E.player('rabbit').character,'jonah');assert.equal(E.travelers.cheetah.name,'Prem');});
test('rare triple crossings need a third boost and are clearable',()=>{const stage=E.level(25),gap=E.obstacles(stage.seed,0,stage.length,25).find(o=>o.triple);assert.equal(gap.width,100);function crossing(boosts){const p=E.player('jonah',25);p.x=gap.x-4;p.edge=p.x-140;E.jump(p);for(let i=0;i<240&&p.alive&&p.x<gap.x+gap.width+2;i++){if(p.jumps===1&&p.x>=gap.x+31)E.jump(p);if(boosts===3&&p.jumps===2&&p.x>=gap.x+70)E.jump(p);E.step(p,1/120,stage.seed,i/120);}return p;}assert.equal(crossing(2).alive,false);const p=crossing(3);assert.ok(p.alive);assert.ok(p.x>gap.x+gap.width);});
test('finishing a level emits completion once and freezes at the finish',()=>{const p=E.player('stickman',4);p.x=E.level(4).length-1;p.edge=p.x-80;let n=0;E.step(p,.1,E.level(4).seed,0,t=>{if(t==='complete')n++;});assert.ok(p.completed);assert.equal(p.x,E.level(4).length);E.step(p,1,71,1,()=>n++);assert.equal(n,1);const retry=E.player(p.character,p.level);assert.equal(retry.x,0);assert.equal(retry.flame,100);assert.equal(retry.level,4);});
test('no intermediate lantern checkpoints remain',()=>{const p=E.player();p.x=249;p.edge=170;run(p,.1);assert.equal(p.checkpoint,0);});
test('flame exhaustion stops the run',()=>{const p=E.player();p.flame=.01;p.sprint=true;run(p,.1);assert.equal(p.alive,false);assert.equal(p.reason,'The wind took your flame.');});
test('difficulty bands apply at the intended boundaries with easier flame use',()=>{for(const l of E.levels)assert.equal(l.difficulty,l.id<=5?'Easy':l.id<=15?'Medium':l.id<=20?'Hard':'Very hard');const easy=E.player('jonah',1),hard=E.player('jonah',25);for(const p of [easy,hard]){p.x=-1000;p.edge=-1140;p.sprint=true;run(p,.5);}assert.ok(easy.flame>hard.flame);assert.ok(E.player('jonah',1).edge<E.player('jonah',25).edge);});
test('gap counts match the difficulty band, with safe recovery and three refill posts',()=>{for(const l of E.levels){const route=E.obstacles(l.seed,0,l.length,l.id);assert.equal(l.length,l.id<10?2000+(l.id-1)*250:l.id<20?4000+(l.id-9)*500:9000+(l.id-19)*10000);const counts=[[3,1,1],[4,2,1],[5,3,1],[7,3,2]][l.tier];assert.equal(route.filter(o=>o.type==='gap'&&!o.wide).length,counts[0]-(l.maxJumps>3?1:0));assert.equal(route.filter(o=>o.jumpsRequired===2).length,counts[1]);assert.equal(route.filter(o=>o.triple).length,counts[2]);for(let i=1;i<route.length;i++)assert.ok(route[i].x-route[i-1].x-route[i-1].width>=50,'space between hazards');assert.ok(route.filter(o=>o.type!=='gap').length>=10);const posts=E.lights(l.seed,l.id);assert.equal(posts.length,3);for(const post of posts)assert.ok(route.every(o=>post.x<o.x-6||post.x>o.x+o.width+6));}});
test('each refill restores flame once without changing the retry point',()=>{const l=E.level(1),post=E.lights(l.seed,1)[0],p=E.player();p.x=post.x-1;p.edge=p.x-140;p.flame=25;for(const o of E.obstacles(l.seed,0,p.x))p.passed[o.id]=true;let n=0;E.step(p,.03,l.seed,0,k=>{if(k==='refill')n++;});assert.equal(p.flame,100);assert.equal(n,1);assert.equal(p.score,75);assert.equal(p.checkpoint,0);p.flame=40;E.step(p,.03,l.seed,0,k=>{if(k==='refill')n++;});assert.equal(n,1);assert.ok(p.flame<41);assert.equal(E.player(p.character,p.level).x,0);});


test('level one teaches jumping before sliding and slide blocks require a slide',()=>{const l=E.level(1),hazards=E.obstacles(l.seed,0,l.length,1);assert.equal(hazards[0].type,'gap');assert.equal(hazards.find(o=>o.type!=='gap').type,'rope');const beam=hazards.find(o=>o.type==='beam');for(const sliding of [false,true]){const p=E.player();p.x=beam.x-1;p.edge=p.x-140;if(sliding)E.slide(p);else E.jump(p);E.step(p,.03,l.seed,0);assert.equal(p.alive,sliding);}});
