// Optional authoritative multiplayer service. Node 18+ recommended; no npm dependencies.
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const E=require('../web/public/engine.js');
const PORT=Number(process.env.PORT||8787),ROOT=path.resolve(__dirname,'../web/public');
const dataFile=process.env.SCORE_FILE||path.join(__dirname,'scores.json');
const origins=new Set(['https://appassets.androidplatform.net',`http://localhost:${PORT}`,`http://127.0.0.1:${PORT}`,...(process.env.ALLOWED_ORIGINS||'').split(',').filter(Boolean)]);
const rooms=new Map(),sessions=new Map(),rates=new Map();let scores=[];
try{scores=JSON.parse(fs.readFileSync(dataFile,'utf8'));}catch{}
const token=()=>crypto.randomBytes(24).toString('hex');
function snapshot(r){return {code:r.code,seed:r.seed,level:r.level,startAt:r.startAt,now:Date.now(),ended:r.ended,players:r.players.map(p=>({name:p.name,x:p.game.x,y:p.game.y,slide:p.game.slide,flame:p.game.flame,alive:p.game.alive,score:p.game.score,checkpoint:p.game.checkpoint,edge:p.game.edge,character:p.game.character,level:p.game.level,completed:p.game.completed,jumps:p.game.jumps,motion:p.game.motion,reason:p.game.reason,passed:p.game.passed}))};}
function saveScores(){try{fs.writeFileSync(dataFile+'.tmp',JSON.stringify(scores));fs.renameSync(dataFile+'.tmp',dataFile);}catch(e){console.error('Score persistence failed:',e.message);}}
function end(r){if(r.ended)return;r.ended=true;r.finishedAt=Date.now();for(const p of r.players)scores.push({name:p.name,distance:Math.floor(p.game.x),score:Math.floor(p.game.x+p.game.score),at:Date.now()});scores=scores.filter(s=>s.at>Date.now()-7*864e5).sort((a,b)=>b.score-a.score).slice(0,100);saveScores();}
let last=Date.now(),carry=0;
const tick=setInterval(()=>{const now=Date.now();carry+=Math.min((now-last)/1000,.25);last=now;while(carry>=1/60){carry-=1/60;for(const r of rooms.values()){if(!r.startAt||now<r.startAt||r.ended)continue;for(const p of r.players){if(now-p.seen>15000){p.game.alive=false;p.game.reason='Connection lost.';}for(const a of p.actions){if(a==='jump')E.jump(p.game);else if(a==='slide')E.slide(p.game);}p.actions=[];E.step(p.game,1/60,r.seed,0,()=>{});}if(r.players.every(p=>!p.game.alive||p.game.completed)||now-r.startAt>30*60e3)end(r);}}
 for(const [code,r] of rooms){if(now-r.created>35*60e3||(r.ended&&now-r.finishedAt>120e3)){r.players.forEach(p=>sessions.delete(p.token));rooms.delete(code);}}for(const [ip,v]of rates)if(now-v.start>60000)rates.delete(ip);
},1000/60);
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>2048){reject(Error('Request too large'));req.destroy();}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch{reject(Error('Invalid JSON'));}});});}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;if(origin&&!origins.has(origin)){res.writeHead(403);res.end();return;}if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
 const ip=req.socket.remoteAddress,rate=rates.get(ip)||{start:Date.now(),n:0};rates.set(ip,rate);rate.n++;const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};if(rate.n>1200){send(429,{error:'Please slow down.'});return;}
 try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/health'){send(200,{ok:true});return;}if(req.method==='GET'&&url.pathname==='/leaderboard'){send(200,{scores:scores.filter(s=>s.at>Date.now()-7*864e5).slice(0,100)});return;}
 if(req.method==='POST'&&['/rooms','/join'].includes(url.pathname)){if(rooms.size>=100){send(503,{error:'The sky is full. Try again shortly.'});return;}const b=await body(req);const name=typeof b.name==='string'?b.name.trim().slice(0,16):'Traveler';if(!/^[\p{L}\p{N} _-]{1,16}$/u.test(name)){send(400,{error:'Use 1–16 letters or numbers for your name.'});return;}let r;if(url.pathname==='/rooms'){let code;do{code=crypto.randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));r={code,seed:crypto.randomBytes(3).readUIntBE(0,3),level:E.level(Number(b.level)||1).id,created:Date.now(),players:[],startAt:0,ended:false};rooms.set(code,r);}else{r=rooms.get(String(b.code||'').toUpperCase());if(!r||r.players.length!==1||r.startAt){send(404,{error:'Room unavailable. Check the invitation code.'});return;}}
 const key=token(),p={token:key,name,game:E.player('jonah',r.level),actions:[],seen:Date.now(),seq:0};r.players.push(p);sessions.set(key,{r,p});if(r.players.length===2)r.startAt=Date.now()+4000;send(200,{token:key,index:r.players.length-1,...snapshot(r)});return;}
 const key=(req.headers.authorization||'').replace(/^Bearer /,'');const session=sessions.get(key);
 if(req.method==='POST'&&url.pathname==='/state'){if(!session){send(401,{error:'Race expired. Create a new invitation.'});return;}const b=await body(req),{r,p}=session;p.seen=Date.now();if(Number.isSafeInteger(b.seq)&&b.seq>p.seq){p.seq=b.seq;p.game.sprint=b.sprint===true;p.actions=(Array.isArray(b.actions)?b.actions:[]).filter(a=>a==='jump'||a==='slide').slice(0,2);}send(200,snapshot(r));return;}
 if(req.method==='POST'&&url.pathname==='/leave'){if(session){session.p.game.alive=false;session.p.game.reason='Left the journey.';}send(200,{ok:true});return;}
 if(req.method==='GET'&&/^\/(?:[a-zA-Z0-9_.-]+)?$/.test(url.pathname)){const file=path.join(ROOT,url.pathname==='/'?'index.html':url.pathname.slice(1));if(fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file),mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime});fs.createReadStream(file).pipe(res);return;}}send(404,{error:'Not found'});
 }catch(e){if(!res.headersSent)send(400,{error:'Invalid request'});}});
if(require.main===module)server.listen(PORT,'0.0.0.0',()=>console.log(`VaVi Lantern service and preview: http://localhost:${PORT}`));
module.exports={server,rooms,sessions,stop:()=>clearInterval(tick)};
